### ISSUE TITLE
Feature: Send parameter to hass.agent command like in IR devices

### ISSUE THREAD

**Issue by urri34** [hass-agent/HASS.Agent#190]
Please make sure that the feature you'd like to request is not already requested :)

----

**Is your feature request related to a problem? Please describe.**
I make scripts that work for me in my LAN, they onlyuse one variable, the IP. I like to call them thru Home Assistant buttons. That home assistant buttons call hass.agernt commands that execute the script with the desired IP parameter. I need to have one command in hass.agent for each IP I want to use the script on. There is no option to send a parameter from Home Assistant to hass.agent commands.

**Describe the solution you'd like**
Working with Home Assistant I realized that the infra red devices can be the solution. You can call an infrared device with a parameter (in that case the infrared signal code to send)

**Describe alternatives you've considered**
I'm not able to find any alternative that is not the 1 ip -> 1 command option. And it works really nice but it's hard to mantain.

**Additional context**
none

**Comment by amadeo-alex** [comment]
Hello, just to confirm some stuff as I'm not sure I understand everything: you'd like for PowershellCommand to accept arguments?

**Comment by urri34** [comment]
Yes but the arguments should be send from the HA. Same script but different arguments.

**Comment by amadeo-alex** [comment]
I might not be catch everything but I think it's already supported.
Example:
```
action: mqtt.publish
data:
  topic: homeassistant/button/AMADEO-PC/powershell/action
  payload: sum argument 4 the script
```
Command:
![obraz](https://github.com/user-attachments/assets/8e0b7e45-0535-4eb6-a17b-44bacfd0f3da)

script2.ps1:
```
$wshell = New-Object -ComObject Wscript.Shell
$wshell.Popup("runs " + $PsBoundParameters.Values + $args,1,"Done",0x1)
$PsBoundParameters.Values >> sumlogs2.txt
```

Result:
![obraz](https://github.com/user-attachments/assets/898e2caa-102d-41ff-9a03-e902caf4d287)

**Comment by urri34** [comment]
You catch it perfectly! It was just me that I was not able to think about the kind of solution you are proposing. Sending it thru the payload and receiving it thru the PsBoundParameters.Values is the point.

SOLVED

Thank you very much for your time!

**Comment by amadeo-alex** [comment]
Closing as solved :)

**Comment by AJolly** [comment]
For this to work do we have to use a custom mqtt action?  / It'd be nice if the ability to pass parameters was mentioned in the action page. It does work well though! 
```

alias: "PC: Adjust Monitor Brightness Based on Room Light"
description: >-
  Calculates target brightness and only runs if it differs from the last set
  value.
triggers:
  - entity_id: sensor.brightness_smoothed_lowpass
    trigger: state
    enabled: true
  - trigger: state
    entity_id:
      - button.tiny_brightness
    from: unavailable
  - trigger: state
    entity_id:
      - button.tiny_brightness
    from: unknown
conditions:
  - condition: template
    value_template: "{{ target_brightness != last_set_brightness }}"
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      topic: homeassistant/button/tiny/brightness/action
      payload: >-
        {{ target_brightness }} {{ states('sensor.brightness_smoothed_lowpass')
        | int }}lux
      retain: false
  - target:
      entity_id: input_number.pc_monitor_last_brightness
    data:
      value: "{{ target_brightness }}"
    action: input_number.set_value
mode: single
variables:
  target_brightness: >
    {% set lux = states('sensor.brightness_smoothed_lowpass') | int(0) %} {% if
    lux <= 15 %}
      0
    {% elif lux >= 170 %}
      100
    {% else %}
      {{ ((lux - 15) / (170 - 15) * 100) | round(0) }}
    {% endif %}
  last_set_brightness: "{{ states('input_number.pc_monitor_last_brightness') | int }}"

```
