### ISSUE TITLE
Bug: Image nbotification not displaying image

### ISSUE THREAD

**Issue by Alby247** [hass-agent/HASS.Agent#209]
HAOS on bare metal

Core 2024.12.5
Supervisor 2024.12.0
Operating System 14.1
Frontend 20241127.8

Hass.agent integration 2.1.0-beta1 installed via HACS.

Hass. Agent installed on Win11 PC.

Show test notification works fine, displays image of the kitten.

Set up automation to display image from security camera:

```
action: notify.acerlaptop
data:
  message: Person at front door
  data:
    image: http://192.168.10.5:8123/config/www/frontdoor.jpg
```

Notification works with message but no image.

The image appears to be being copied to the cache folder (default to "C:\Users\myusername\AppData\Local\HASS.Agent\Client\cache\images\20241226145810_64abcece.jpg"

But when viewing this image it is not viewable in Win11.  The image at config/www/ is viewable in Win11, so it seems the file is being corrupted when it is copied to the cache folder.  Image is jpg 1280x720, 397kb, 9dpi 24 bit.  Tried png version, same problem.
