### ISSUE TITLE
Feature: notify groups notify.yaml

### ISSUE THREAD

**Issue by Eckart0** [hass-agent/HASS.Agent#268]
Hello,

with the LAB02 version I was able to create groups of computers for notifications in notify.yaml. With the current version I can no longer do this. My code in notify.yaml:

`- name: computers
  platform: group
  services:
    - service: notify.mypc1
    - service: notify.mypc2
    - service: notify.hp-spectre`

Direct notifications via automation or script are possible.

Is there a feature missing from the previous version or is my code wrong?

Regards, Eckart

**Comment by amadeo-alex** [comment]
Hello,

I'm not sure about the original version but I remember there was a question like this before regarding the fork.
Could you please see below setup that I have - which of course works, tested a second ago :D

configuration.yaml entry:
```
notify:
  - platform: group
    name: "Sum Notify Group"
    services:
      - action: mobile_app_sm_f741b
      - action: amadeo_pc
```

service/action call:
```
action: notify.sum_notify_group
data:
  title: Fancy Title
  message: Banana
```
