### ISSUE TITLE
Feature: User-Confirmation of Notification-Popup on PC

### ISSUE THREAD

**Issue by stvogel** [hass-agent/HASS.Agent#271]
I'm not sure if this is possible already.
I'd like to get a notification that a device (e.g. a motionblind) needs to be recharged.
So I'm having this notification:
```
alias: TestNotification
sequence:
  - service: notify.mypc
    data:
      title: Recharge
      message: Please recharge Rollerblind ...
```
This pops up on "mypc" for a few seconds and than disappears.
I'd like the notification to stay open until the user actively closes it via a button. Else I risk that the notification maybe disappeared before the user noticing it.

By the way ... thanks for this great plugin. It really helps a lot.

**Comment by amadeo-alex** [comment]
Hello, could you please try below and see if it does what you'd like?
```
service: notify.amadeo_pc
data:
  title: "I'm sticky"
  message: Gonna stay here I think
  data:
    actions:
      - action: "ok"
        title: "Ok"
    sticky: true
```
