### ISSUE TITLE
Feature: Expose display as light to HA

### ISSUE THREAD

**Issue by AJolly** [hass-agent/HASS.Agent#93]
It's nice that Hass Agent lets us use Display as a sensor, but I'd be even nicer if it could expose Displays as Lights to HA.  This would let us read / be able to control brightness from HA.  

I've got ambient light sensors reporting to HA already, would be great to be able to use that as input to control my desktops monitor brightness!

**Comment by amadeo-alex** [comment]
I like the idea, there might be however one (or more huh) issue/s.
Monitor brightness is as convoluted as the DPI is in Windows - it differs between desktops and laptops and then there is no certainty that it will actually work on device X or Y.

I'll play around with various options and update here as needed.

**Comment by amadeo-alex** [comment]
For reference purposes: this software seems to be working with my monitors - https://apps.microsoft.com/detail/9nw33j738bl0?hl=en-us&gl=US (assumption is DDC/CI)

**Comment by AJolly** [comment]
Yeah there's a bunch of ways to control monitor brightness, This is my usual go to - https://www.nirsoft.net/utils/control_my_monitor.html

I can already use HA to call control my monitor, but only by running it as a custom command.

The key request for me is I want it exposed as a Light to HA, so that way I can use adaptive lighting or another automation to use my existing lux meter when deciding what brightness to set.    There's a ton of automations in HA for controlling lights, HA just needs to be able to see the PC displays as a light.  

Or If you have altered suggestions that'd be great, it's been weirdly hard finding documentation or even being able to buy a desktop light sensor.

Anyways, I appreciate the project!

**Comment by Jatoxo** [comment]
It's a little annoying but it's already possible to do this with a template light. You just have to add commands for turning on/off the monitor, then call those from the template light. You can control the brightness with an action command in HASS.Agent that supplies the brightness level to some command on your PC that can change the brightness. Here's what it could look like:

```yaml
light:
  - platform: template
    lights:
      my_pc_monitor:
        unique_id: pc_monitor
        friendly_name: "PC Monitor"
        icon_template: >
            mdi:monitor
        availability_template: "{{not is_state('button.pc_monitor_on', 'unavailable')}}"
        set_level:
          - service: mqtt.publish
            data:
              payload: "{{((brightness) / 255 * 100)|int }}"
              topic: homeassistant/button/Jatoxo/setdim/action 
        turn_on:
          - service: button.press
            entity_id: button.pc_monitor_on
        turn_off:
          - service: button.press
            entity_id: button.pc_monitor_off
```

In my case the brightness value gets passed to a python script which controls the brightness through another program
